package com.lbs.recording.interfaces;

import com.lbs.recording.JLbsRecordItem;
import java.util.ArrayList;

public interface ILbsEventRecorder {
  void addRecordItem(JLbsRecordItem paramJLbsRecordItem, Object paramObject);
  
  void addFormSnapshot(Object paramObject);
  
  void addComparisonItems(Object paramObject);
  
  void addVariableItems(Object paramObject);
  
  void setSecondaryKey(Object paramObject);
  
  void setLastItemAsSaveOperation();
  
  void finalizeBeforeRecordFlush();
  
  void insertVP();
  
  void switchAutoVPGeneration();
  
  void insertAutoGeneratedVPs();
  
  void recordTest();
  
  void recordTest(boolean paramBoolean, String paramString);
  
  void registerVariable(int paramInt, String paramString, Object paramObject);
  
  boolean variableRegisteredPreviously(int paramInt, String paramString);
  
  String getNextVariableName(int paramInt);
  
  ArrayList getRegisteredVariableList(int paramInt);
  
  void processDataGridForSecondaryKeySelect(Object paramObject);
  
  Object getSecondaryKeyProperties(String paramString);
  
  void generateEmulating();
  
  Object getEmulatingPane();
  
  void setEmulatingPane(Object paramObject);
  
  boolean isJustInTime();
  
  void setJustInTime(boolean paramBoolean);
  
  boolean isLookup();
  
  void setLookup(boolean paramBoolean);
}


/* Location:              C:\Users\Furkan\Desktop\logo\Components.jar!\com\lbs\recording\interfaces\ILbsEventRecorder.class
 * Java compiler version: 8 (52.0)
 * JD-Core Version:       1.1.3
 */